"""
HTML Report Generator for ESXi Stealth VA

Produces a single, self-contained HTML file for human review.
Uses an embedded CSS design for a professional look in air-gapped environments.
"""

import os
import json
import logging
from pathlib import Path
from datetime import datetime
from typing import Dict, Any

from orchestrator.models import AssessmentReport

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ESXi Security Audit - {week}</title>
    <style>
        :root {{
            --bg: #0f172a;
            --card-bg: #1e293b;
            --text: #f1f5f9;
            --muted: #94a3b8;
            --primary: #38bdf8;
            --critical: #ef4444;
            --high: #f97316;
            --medium: #facc15;
            --low: #4ade80;
            --info: #94a3b8;
            --border: #334155;
        }}
        body {{
            background: var(--bg);
            color: var(--text);
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 2rem;
        }}
        header {{
            border-bottom: 2px solid var(--border);
            margin-bottom: 2rem;
            padding-bottom: 1rem;
        }}
        .badge {{
            padding: 0.25rem 0.5rem;
            border-radius: 0.375rem;
            font-size: 0.75rem;
            font-weight: 600;
            text-transform: uppercase;
        }}
        .badge-critical {{ background: var(--critical); color: #fff; }}
        .badge-high {{ background: var(--high); color: #fff; }}
        .badge-medium {{ background: var(--medium); color: #000; }}
        .badge-low {{ background: var(--low); color: #000; }}
        .badge-info {{ background: var(--info); color: #000; }}
        
        .summary-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin-bottom: 2rem;
        }}
        .card {{
            background: var(--card-bg);
            padding: 1.5rem;
            border-radius: 0.75rem;
            border: 1px solid var(--border);
        }}
        .card h3 {{ margin: 0 0 0.5rem 0; color: var(--muted); font-size: 0.875rem; }}
        .card p {{ margin: 0; font-size: 1.5rem; font-weight: bold; border-left: 4px solid var(--primary); padding-left: 0.5rem; }}
        
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 2rem;
            background: var(--card-bg);
            border-radius: 0.75rem;
            overflow: hidden;
        }}
        th, td {{
            text-align: left;
            padding: 1rem;
            border-bottom: 1px solid var(--border);
        }}
        th {{ background: rgba(255,255,255,0.05); color: var(--muted); text-transform: uppercase; font-size: 0.75rem; }}
        
        .finding-row:hover {{ background: rgba(255,255,255,0.02); }}
        
        .delta-resolved {{ color: var(--low); }}
        .delta-new {{ color: var(--critical); }}
        
        .footer {{ margin-top: 4rem; text-align: center; color: var(--muted); font-size: 0.875rem; }}
    </style>
</head>
<body>
    <header>
        <h1>ESXi Security Audit Report</h1>
        <p style="color: var(--muted)">Week: {week} | Run ID: {run_id}</p>
    </header>

    <div class="summary-grid">
        <div class="card"><h3>Total Hosts</h3><p>{total_hosts}</p></div>
        <div class="card"><h3>Vulnerabilities</h3><p>{total_vulns}</p></div>
        <div class="card"><h3>Crypto Issues</h3><p>{total_crypto}</p></div>
        <div class="card"><h3>Deltas</h3><p style="border-color: var(--medium)">New: {delta_new} | Res: {delta_res}</p></div>
    </div>

    <h2>Vulnerability Findings</h2>
    <table>
        <thead>
            <tr>
                <th>Severity</th>
                <th>Target</th>
                <th>Vulnerability</th>
                <th>Scanner</th>
            </tr>
        </thead>
        <tbody>
            {vuln_rows}
        </tbody>
    </table>

    <div class="footer">
        Generated by Antigravity ESXi Stealth Framework v2.1.0 — CyberArk Audit Trail Verified
    </div>
</body>
</html>
"""

def generate_report(report: AssessmentReport, output_path: str):
    """Generate the HTML report from the AssessmentReport object."""
    stats = report.summary()
    
    vuln_rows = ""
    # Add Nuclei findings
    for v in report.findings_vulns:
        sev_class = f"badge-{v.severity.lower()}"
        vuln_rows += f"""
        <tr class="finding-row">
            <td><span class="badge {sev_class}">{v.severity}</span></td>
            <td>{v.host}:{v.port}</td>
            <td><strong>{v.name}</strong><br><small style='color:var(--muted)'>{v.description}</small></td>
            <td>{v.scanner}</td>
        </tr>
        """
        
    # Add Crypto findings (only if grade < A)
    for c in report.findings_crypto:
        if c.grade not in ("A+", "A"):
            sev_class = f"badge-{c.severity.lower()}"
            vuln_rows += f"""
            <tr class="finding-row">
                <td><span class="badge {sev_class}">{c.grade}</span></td>
                <td>{c.host}:{c.port}</td>
                <td><strong>Suboptimal TLS Config</strong><br><small style='color:var(--muted)'>Grade: {c.grade}. {', '.join(c.vulnerabilities[:3])}</small></td>
                <td>{c.scan_method}</td>
            </tr>
            """

    delta_new = report.delta.summary.get("new", 0) if report.delta else 0
    delta_res = report.delta.summary.get("resolved", 0) if report.delta else 0

    html_content = HTML_TEMPLATE.format(
        week=report.metadata.scan_week,
        run_id=report.metadata.run_id,
        total_hosts=stats['total_hosts'],
        total_vulns=stats['total_vuln_findings'],
        total_crypto=stats['total_crypto_findings'],
        delta_new=delta_new,
        delta_res=delta_res,
        vuln_rows=vuln_rows
    )

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    logger.info(f"HTML report generated: {output_path}")
